import fs from "node:fs";
import path from "node:path";

export const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const CURRENT_VERSION_RE = /\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?/;

const read = (root, rel) => fs.readFileSync(path.join(root, rel), "utf8");
const write = (root, rel, content) => fs.writeFileSync(path.join(root, rel), content);
const detectEol = (text) => (text.includes("\r\n") ? "\r\n" : "\n");
const jsonText = (source, value) =>
  JSON.stringify(value, null, 2).replace(/\n/g, detectEol(source)) + detectEol(source);

function replaceExactly(text, regex, replacement, expectedCount, label) {
  let count = 0;
  const next = text.replace(regex, (...args) => {
    count += 1;
    return typeof replacement === "function" ? replacement(...args) : replacement;
  });
  if (count !== expectedCount) {
    throw new Error(`${label}: expected ${expectedCount} version marker(s), found ${count}`);
  }
  return next;
}

function markedVersions(text) {
  const regex =
    /data-app-version(?:=(?:"[^"]*"|'[^']*'|[^\s>]+))?[^>]*>v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)</g;
  return [...text.matchAll(regex)].map((match) => match[1]);
}

export function readCanonicalVersion(root) {
  const version = read(root, "VERSION").trim();
  if (!SEMVER_RE.test(version)) throw new Error(`Invalid SemVer in VERSION: ${version}`);
  return version;
}

export function syncVersionTargets(root, version) {
  if (!SEMVER_RE.test(version)) throw new Error(`Invalid SemVer: ${version}`);

  const pkgPath = path.join(root, "package.json");
  const pkgSource = fs.readFileSync(pkgPath, "utf8");
  const pkg = JSON.parse(pkgSource);
  pkg.version = version;
  fs.writeFileSync(pkgPath, jsonText(pkgSource, pkg));

  const npmLockPath = path.join(root, "package-lock.json");
  if (fs.existsSync(npmLockPath)) {
    const lockSource = fs.readFileSync(npmLockPath, "utf8");
    const lock = JSON.parse(lockSource);
    lock.version = version;
    if (lock.packages?.[""]) lock.packages[""].version = version;
    fs.writeFileSync(npmLockPath, jsonText(lockSource, lock));
  }

  const tauriPath = path.join(root, "src-tauri", "tauri.conf.json");
  const tauriSource = fs.readFileSync(tauriPath, "utf8");
  const tauri = JSON.parse(tauriSource);
  tauri.version = version;
  fs.writeFileSync(tauriPath, jsonText(tauriSource, tauri));

  let cargo = read(root, "src-tauri/Cargo.toml");
  cargo = replaceExactly(
    cargo,
    /(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"/m,
    (_match, prefix) => `${prefix}"${version}"`,
    1,
    "Cargo.toml package version",
  );
  write(root, "src-tauri/Cargo.toml", cargo);

  const cargoLockPath = path.join(root, "src-tauri", "Cargo.lock");
  if (fs.existsSync(cargoLockPath)) {
    let lock = fs.readFileSync(cargoLockPath, "utf8");
    lock = replaceExactly(
      lock,
      /(\[\[package\]\]\r?\nname = "imagelore"\r?\nversion = ")[^"]+(")/,
      (_match, prefix, suffix) => `${prefix}${version}${suffix}`,
      1,
      "Cargo.lock ImageLore version",
    );
    fs.writeFileSync(cargoLockPath, lock);
  }

  const generatedPath = path.join(root, "src", "version.ts");
  const generatedSource = fs.existsSync(generatedPath)
    ? fs.readFileSync(generatedPath, "utf8")
    : "";
  const generatedEol = detectEol(generatedSource);
  fs.writeFileSync(
    generatedPath,
    `// Generated by scripts/sync_version.mjs. Do not edit by hand.${generatedEol}export const APP_VERSION = ${JSON.stringify(version)};${generatedEol}`,
  );

  let readme = read(root, "README.md");
  readme = replaceExactly(
    readme,
    /^# ImageLore v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?([ \t]*)(\r?)$/m,
    (_match, spaces, cr) => `# ImageLore v${version}${spaces}${cr}`,
    1,
    "README current version heading",
  );
  write(root, "README.md", readme);

  for (const [rel, expectedCount] of [
    ["docs/UI_PREVIEW.html", 2],
    ["docs/og.svg", 1],
  ]) {
    let text = read(root, rel);
    text = replaceExactly(
      text,
      /(<[^>]*\bdata-app-version(?:=(?:"[^"]*"|'[^']*'|[^\s>]+))?[^>]*>)v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(<\/[^>]+>)/g,
      (_match, open, close) => `${open}v${version}${close}`,
      expectedCount,
      rel,
    );
    write(root, rel, text);
  }
}

export function collectVersionEntries(root) {
  const entries = [];
  const expected = readCanonicalVersion(root);
  const push = (label, value) => entries.push({ label, value: value ?? null });

  push("VERSION", expected);

  const pkg = JSON.parse(read(root, "package.json"));
  push("package.json", pkg.version);

  const npmLock = JSON.parse(read(root, "package-lock.json"));
  push("package-lock.json root", npmLock.version);
  push("package-lock.json workspace", npmLock.packages?.[""]?.version);

  const tauri = JSON.parse(read(root, "src-tauri/tauri.conf.json"));
  push("tauri.conf.json", tauri.version);

  const cargo = read(root, "src-tauri/Cargo.toml").match(
    /\[package\][\s\S]*?version\s*=\s*"([^"]+)"/,
  )?.[1];
  push("Cargo.toml", cargo);

  const cargoLock = read(root, "src-tauri/Cargo.lock").match(
    /\[\[package\]\]\r?\nname = "imagelore"\r?\nversion = "([^"]+)"/,
  )?.[1];
  push("Cargo.lock", cargoLock);

  const generated = read(root, "src/version.ts").match(/APP_VERSION = "([^"]+)"/)?.[1];
  push("src/version.ts", generated);

  const readme = read(root, "README.md").match(
    /^# ImageLore v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)[ \t]*\r?$/m,
  )?.[1];
  push("README.md heading", readme);

  const previewVersions = markedVersions(read(root, "docs/UI_PREVIEW.html"));
  if (previewVersions.length !== 2) {
    push("UI_PREVIEW markers", `marker-count:${previewVersions.length}`);
  } else {
    previewVersions.forEach((value, index) => push(`UI_PREVIEW marker ${index + 1}`, value));
  }

  const ogVersions = markedVersions(read(root, "docs/og.svg"));
  if (ogVersions.length !== 1) {
    push("OG SVG marker", `marker-count:${ogVersions.length}`);
  } else {
    push("OG SVG marker", ogVersions[0]);
  }

  return { expected, entries };
}
