import fs from 'node:fs';
import path from 'node:path';

export const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const SEMVER_CAPTURE = '(\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?)';

const read = (root, rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const write = (root, rel, content) => fs.writeFileSync(path.join(root, rel), content);

function replaceExactly(text, regex, replacement, expectedCount, label) {
  let count = 0;
  const next = text.replace(regex, (...args) => {
    count += 1;
    return typeof replacement === 'function' ? replacement(...args) : replacement;
  });
  if (count !== expectedCount) {
    throw new Error(`${label}: expected ${expectedCount} version marker(s), found ${count}`);
  }
  return next;
}

function markedVersions(text) {
  const regex = new RegExp(`data-app-version(?:=(?:"[^"]*"|'[^']*'|[^\\s>]+))?[^>]*>v${SEMVER_CAPTURE}<`, 'g');
  return [...text.matchAll(regex)].map(match => match[1]);
}

export function readCanonicalVersion(root) {
  const version = read(root, 'VERSION').trim();
  if (!SEMVER_RE.test(version)) throw new Error(`Invalid SemVer in VERSION: ${version}`);
  return version;
}

export function syncVersionTargets(root, version) {
  if (!SEMVER_RE.test(version)) throw new Error(`Invalid SemVer: ${version}`);

  const pkgPath = path.join(root, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.version = version;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  const npmLockPath = path.join(root, 'package-lock.json');
  if (fs.existsSync(npmLockPath)) {
    const lock = JSON.parse(fs.readFileSync(npmLockPath, 'utf8'));
    lock.version = version;
    if (lock.packages?.['']) lock.packages[''].version = version;
    fs.writeFileSync(npmLockPath, JSON.stringify(lock, null, 2) + '\n');
  }

  const tauriPath = path.join(root, 'src-tauri', 'tauri.conf.json');
  const tauri = JSON.parse(fs.readFileSync(tauriPath, 'utf8'));
  tauri.version = version;
  fs.writeFileSync(tauriPath, JSON.stringify(tauri, null, 2) + '\n');

  let cargo = read(root, 'src-tauri/Cargo.toml');
  cargo = replaceExactly(
    cargo,
    /(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"/m,
    (_match, prefix) => `${prefix}"${version}"`,
    1,
    'Cargo.toml package version'
  );
  write(root, 'src-tauri/Cargo.toml', cargo);

  const cargoLockPath = path.join(root, 'src-tauri', 'Cargo.lock');
  if (fs.existsSync(cargoLockPath)) {
    let lock = fs.readFileSync(cargoLockPath, 'utf8');
    lock = replaceExactly(
      lock,
      /(\[\[package\]\]\r?\nname = "imagelore"\r?\nversion = ")[^"]+(")/,
      (_match, prefix, suffix) => `${prefix}${version}${suffix}`,
      1,
      'Cargo.lock ImageLore version'
    );
    fs.writeFileSync(cargoLockPath, lock);
  }

  write(
    root,
    'src/version.ts',
    `// Generated by scripts/sync_version.mjs. Do not edit by hand.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`
  );

  let readme = read(root, 'README.md');
  readme = replaceExactly(
    readme,
    /^# ImageLore v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?[ \t]*\r?$/m,
    `# ImageLore v${version}`,
    1,
    'README current version heading'
  );
  write(root, 'README.md', readme);

  for (const [rel, expectedCount] of [['docs/UI_PREVIEW.html', 2], ['docs/og.svg', 1]]) {
    let text = read(root, rel);
    text = replaceExactly(
      text,
      new RegExp(`(<[^>]*\\bdata-app-version(?:=(?:"[^"]*"|'[^']*'|[^\\s>]+))?[^>]*>)v${SEMVER_CAPTURE}(<\\/[^>]+>)`, 'g'),
      (_match, open, _oldVersion, close) => `${open}v${version}${close}`,
      expectedCount,
      rel
    );
    write(root, rel, text);
  }
}

export function collectVersionEntries(root) {
  const entries = [];
  const expected = readCanonicalVersion(root);
  const push = (label, value) => entries.push({ label, value: value ?? null });

  push('VERSION', expected);

  const pkg = JSON.parse(read(root, 'package.json'));
  push('package.json', pkg.version);

  const npmLock = JSON.parse(read(root, 'package-lock.json'));
  push('package-lock.json root', npmLock.version);
  push('package-lock.json workspace', npmLock.packages?.['']?.version);

  const tauri = JSON.parse(read(root, 'src-tauri/tauri.conf.json'));
  push('tauri.conf.json', tauri.version);

  const cargo = read(root, 'src-tauri/Cargo.toml')
    .match(/\[package\][\s\S]*?version\s*=\s*"([^"]+)"/)?.[1];
  push('Cargo.toml', cargo);

  const cargoLock = read(root, 'src-tauri/Cargo.lock')
    .match(/\[\[package\]\]\r?\nname = "imagelore"\r?\nversion = "([^"]+)"/)?.[1];
  push('Cargo.lock', cargoLock);

  const generated = read(root, 'src/version.ts')
    .match(/APP_VERSION = "([^"]+)"/)?.[1];
  push('src/version.ts', generated);

  const readme = read(root, 'README.md')
    .match(new RegExp(`^# ImageLore v${SEMVER_CAPTURE}[ \\t]*\\r?import fs from 'node:fs';
import path from 'node:path';

export const SEMVER_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const SEMVER_CAPTURE = '(\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?)';

const read = (root, rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const write = (root, rel, content) => fs.writeFileSync(path.join(root, rel), content);

function replaceExactly(text, regex, replacement, expectedCount, label) {
  let count = 0;
  const next = text.replace(regex, (...args) => {
    count += 1;
    return typeof replacement === 'function' ? replacement(...args) : replacement;
  });
  if (count !== expectedCount) {
    throw new Error(`${label}: expected ${expectedCount} version marker(s), found ${count}`);
  }
  return next;
}

function markedVersions(text) {
  const regex = new RegExp(`data-app-version(?:=(?:"[^"]*"|'[^']*'|[^\\s>]+))?[^>]*>v${SEMVER_CAPTURE}<`, 'g');
  return [...text.matchAll(regex)].map(match => match[1]);
}

export function readCanonicalVersion(root) {
  const version = read(root, 'VERSION').trim();
  if (!SEMVER_RE.test(version)) throw new Error(`Invalid SemVer in VERSION: ${version}`);
  return version;
}

export function syncVersionTargets(root, version) {
  if (!SEMVER_RE.test(version)) throw new Error(`Invalid SemVer: ${version}`);

  const pkgPath = path.join(root, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.version = version;
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

  const npmLockPath = path.join(root, 'package-lock.json');
  if (fs.existsSync(npmLockPath)) {
    const lock = JSON.parse(fs.readFileSync(npmLockPath, 'utf8'));
    lock.version = version;
    if (lock.packages?.['']) lock.packages[''].version = version;
    fs.writeFileSync(npmLockPath, JSON.stringify(lock, null, 2) + '\n');
  }

  const tauriPath = path.join(root, 'src-tauri', 'tauri.conf.json');
  const tauri = JSON.parse(fs.readFileSync(tauriPath, 'utf8'));
  tauri.version = version;
  fs.writeFileSync(tauriPath, JSON.stringify(tauri, null, 2) + '\n');

  let cargo = read(root, 'src-tauri/Cargo.toml');
  cargo = replaceExactly(
    cargo,
    /(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"/m,
    (_match, prefix) => `${prefix}"${version}"`,
    1,
    'Cargo.toml package version'
  );
  write(root, 'src-tauri/Cargo.toml', cargo);

  const cargoLockPath = path.join(root, 'src-tauri', 'Cargo.lock');
  if (fs.existsSync(cargoLockPath)) {
    let lock = fs.readFileSync(cargoLockPath, 'utf8');
    lock = replaceExactly(
      lock,
      /(\[\[package\]\]\r?\nname = "imagelore"\r?\nversion = ")[^"]+(")/,
      (_match, prefix, suffix) => `${prefix}${version}${suffix}`,
      1,
      'Cargo.lock ImageLore version'
    );
    fs.writeFileSync(cargoLockPath, lock);
  }

  write(
    root,
    'src/version.ts',
    `// Generated by scripts/sync_version.mjs. Do not edit by hand.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`
  );

  let readme = read(root, 'README.md');
  readme = replaceExactly(
    readme,
    /^# ImageLore v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?[ \t]*\r?$/m,
    `# ImageLore v${version}`,
    1,
    'README current version heading'
  );
  write(root, 'README.md', readme);

  for (const [rel, expectedCount] of [['docs/UI_PREVIEW.html', 2], ['docs/og.svg', 1]]) {
    let text = read(root, rel);
    text = replaceExactly(
      text,
      new RegExp(`(<[^>]*\\bdata-app-version(?:=(?:"[^"]*"|'[^']*'|[^\\s>]+))?[^>]*>)v${SEMVER_CAPTURE}(<\\/[^>]+>)`, 'g'),
      (_match, open, _oldVersion, close) => `${open}v${version}${close}`,
      expectedCount,
      rel
    );
    write(root, rel, text);
  }
}

export function collectVersionEntries(root) {
  const entries = [];
  const expected = readCanonicalVersion(root);
  const push = (label, value) => entries.push({ label, value: value ?? null });

  push('VERSION', expected);

  const pkg = JSON.parse(read(root, 'package.json'));
  push('package.json', pkg.version);

  const npmLock = JSON.parse(read(root, 'package-lock.json'));
  push('package-lock.json root', npmLock.version);
  push('package-lock.json workspace', npmLock.packages?.['']?.version);

  const tauri = JSON.parse(read(root, 'src-tauri/tauri.conf.json'));
  push('tauri.conf.json', tauri.version);

  const cargo = read(root, 'src-tauri/Cargo.toml')
    .match(/\[package\][\s\S]*?version\s*=\s*"([^"]+)"/)?.[1];
  push('Cargo.toml', cargo);

  const cargoLock = read(root, 'src-tauri/Cargo.lock')
    .match(/\[\[package\]\]\r?\nname = "imagelore"\r?\nversion = "([^"]+)"/)?.[1];
  push('Cargo.lock', cargoLock);

  const generated = read(root, 'src/version.ts')
    .match(/APP_VERSION = "([^"]+)"/)?.[1];
  push('src/version.ts', generated);

  const readme = read(root, 'README.md')
    .match(, 'm'))?.[1];
  push('README.md heading', readme);

  const previewVersions = markedVersions(read(root, 'docs/UI_PREVIEW.html'));
  if (previewVersions.length !== 2) {
    push('UI_PREVIEW markers', `marker-count:${previewVersions.length}`);
  } else {
    previewVersions.forEach((value, index) => push(`UI_PREVIEW marker ${index + 1}`, value));
  }

  const ogVersions = markedVersions(read(root, 'docs/og.svg'));
  if (ogVersions.length !== 1) {
    push('OG SVG marker', `marker-count:${ogVersions.length}`);
  } else {
    push('OG SVG marker', ogVersions[0]);
  }

  return { expected, entries };
}
